apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: parking-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - { name: RABBITMQ_DEFAULT_USER, value: "guest" }
            - { name: RABBITMQ_DEFAULT_PASS, value: "guest" }
          ports:
            - containerPort: 5672    # AMQP
            - containerPort: 15672   # Panel de administración web
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: parking-ns
spec:
  selector:
    app: rabbitmq
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: mgmt, port: 15672, targetPort: 15672 }
  type: ClusterIP
